import {metrics,visibleAgents,statusLabels,type Action,type DashboardState,type Agent} from './model';
import {scenarios} from './fixtures';
const icons:Record<string,string>={spark:'<path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6Z"/>',grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',check:'<path d="m5 12 4 4L19 6"/>',clock:'<circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/>',arrow:'<path d="m9 5 7 7-7 7"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="2"/>',cube:'<path d="m12 3 9 5v8l-9 5-9-5V8Zm0 9v9M3 8l9 4 9-4M7 5.8l9 5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>'};
export function icon(name:string){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]??icons.spark}</svg>`;}
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function avatar(a:Agent,large=false){return `<span class="avatar ${large?'large':''}" style="--agent:${a.color}" aria-hidden="true"><span class="avatar-hair ${a.id}"></span><span class="avatar-face"><i></i><i></i></span><span class="avatar-shirt"></span></span>`;}
export function mountDashboard(root:HTMLElement,dispatch:(action:Action)=>void){
 root.innerHTML=`<header class="app-header"><a class="brand" href="/" aria-label="Tafwid home"><span class="brand-mark"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 12h18M16 12v14M7 12v6M25 12v6"/><rect x="4" y="6" width="6" height="6" rx="2"/><rect x="22" y="6" width="6" height="6" rx="2"/><rect x="13" y="23" width="6" height="6" rx="2"/></svg></span>Tafwid<span class="brand-divider"></span><span class="workspace-name">My workspace</span></a><div class="header-right"><span class="sample-badge">${icon('cube')} Sample data</span><span class="owner-avatar" aria-label="Personal workspace">You</span></div></header>
 <main><div class="page-heading"><div><div class="breadcrumb">Workspace <span>/</span> Overview</div><h1>Your team, at work<span>.</span></h1><p>A little perspective on everything your agents are doing.</p></div><label class="scenario-control"><span>Explore the prototype</span><select aria-label="Demo scenario"><option value="active">A productive day</option><option value="empty">An empty office</option><option value="unavailable">Updates unavailable</option></select></label></div>
 <div class="notice" role="status" hidden></div>
 <div class="dashboard-grid"><section class="stats" aria-label="Session stats"><div class="stat"><span class="stat-icon green">${icon('spark')}</span><div><span class="stat-label">Working now</span><div><strong data-metric="working"></strong><span class="stat-note">agents in focus</span></div></div></div><div class="stat"><span class="stat-icon amber">${icon('eye')}</span><div><span class="stat-label">Awaiting review</span><div><strong data-metric="review"></strong><span class="stat-note">ready for a look</span></div></div></div><div class="stat"><span class="stat-icon blue">${icon('check')}</span><div><span class="stat-label">Completed</span><div><strong data-metric="completed"></strong><span class="stat-note">runs this session</span></div></div></div></section>
 <section class="office-panel" aria-labelledby="office-title"><div class="panel-heading"><div class="room-title"><span class="room-icon">${icon('grid')}</span><div><h2 id="office-title">The studio</h2><p>Your team's little corner of the internet</p></div></div><span class="room-count"></span></div><div class="scene-wrap"><div class="scene-host" aria-label="Agent office"></div><div class="scene-watermark">A space for good work.</div></div><div class="office-footer"><span>${icon('cube')} <span>Click an agent to see their work</span></span><span class="view-label">Isometric view</span></div></section>
 <section class="roster-panel" aria-labelledby="roster-title"><div class="roster-heading"><h2 id="roster-title">Your team <span class="team-count"></span></h2><span class="tiny-label">This session</span></div><div class="filters" role="group" aria-label="Filter agents"><button data-filter="all" aria-pressed="true">All agents</button><button data-filter="working" aria-pressed="false">Working</button><button data-filter="attention" aria-pressed="false">Attention</button></div><div class="roster"></div><div class="roster-foot">${icon('info')} <span>Different strengths. Working together.</span></div></section>
 <section class="details" aria-label="Selected agent details"></section></div>
 <footer class="page-footer"><span><span class="footer-dot"></span> A glimpse of your future workspace</span><span>Prototype · Fictional agents & tasks</span></footer></main>`;
 const $=<T extends Element=HTMLElement>(selector:string)=>root.querySelector<T>(selector)!;
 const select=$<HTMLSelectElement>('select');const handler=()=>dispatch({type:'scenario',scenario:scenarios[select.value as keyof typeof scenarios]});select.addEventListener('change',handler);
 const clicks=(e:Event)=>{const el=(e.target as Element).closest<HTMLButtonElement>('button');if(el?.dataset.filter)dispatch({type:'filter',filter:el.dataset.filter as DashboardState['filter']});if(el?.dataset.agent)dispatch({type:'select',id:el.dataset.agent,source:'roster'});};root.addEventListener('click',clicks);
 return {sceneHost:$('.scene-host'),render(s:DashboardState){
  const focused=(document.activeElement as HTMLElement)?.dataset.agent;
  const counts=metrics(s.scenario);for(const [key,value] of Object.entries(counts))$(`[data-metric="${key}"]`).textContent=value===null?'—':String(value).padStart(2,'0');
  select.value=s.scenario.id;$('.team-count').textContent=String(s.scenario.agents.length);$('.room-count').textContent=s.scenario.agents.length?`${s.scenario.agents.length} agents in the studio`:'Room for your next team';
  const notice=$('.notice');notice.hidden=s.scenario.fresh;notice.innerHTML=`${icon('info')}<span><strong>Updates unavailable.</strong> Showing the last sample snapshot. Current activity is unknown.</span>`;
  root.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===s.filter)));
  const agents=visibleAgents(s);$('.roster').innerHTML=agents.length?agents.map(a=>`<button class="agent-card ${a.id===s.selectedId?'selected':''}" data-agent="${a.id}" aria-pressed="${a.id===s.selectedId}">${avatar(a)}<span class="agent-content"><span class="agent-top"><strong>${esc(a.name)}</strong><span class="agent-role">${esc(a.role)}</span></span><span class="agent-task">${esc(a.task)}</span><span class="agent-meta"><span class="status ${a.status}"><span></span>${statusLabels[a.status]}${s.scenario.fresh?'':' · last seen'}</span><span class="elapsed">${a.elapsedSeconds?`${Math.floor(a.elapsedSeconds/60)}m elapsed`:'No active task'}</span></span></span><span class="agent-chevron">${icon('arrow')}</span></button>`).join(''):`<div class="empty-state">${icon('cube')}<h3>${s.scenario.agents.length?'Nothing in this view':'A fresh start'}</h3><p>${s.scenario.agents.length?'Try All agents to see the rest of your team.':'Your agents will appear here when work begins. Explore a productive day above.'}</p></div>`;
  if(focused){root.querySelector<HTMLButtonElement>(`[data-agent="${focused}"]`)?.focus({preventScroll:true});}
  const a=s.scenario.agents.find(a=>a.id===s.selectedId);
  $('.details').innerHTML=a?`<div class="detail-identity">${avatar(a,true)}<div><span class="detail-eyebrow">In focus${s.scenario.fresh?'':' · last sample snapshot'}</span><h2>${esc(a.name)} <span>${esc(a.role)}</span></h2><span class="provider">${a.backend==='gpt'?'GPT · Codex CLI':'Claude Code'}</span></div></div><div class="detail-task"><span class="detail-eyebrow">${a.status==='ready'?'Availability':'Current task'}</span><h3>${esc(a.task)}</h3><span class="status ${a.status}"><span></span>${statusLabels[a.status]}</span></div><div class="detail-next"><span class="detail-eyebrow">What happens next</span><p>${esc(a.nextStep)}</p></div>`:`<div class="detail-empty">Select an agent to take a closer look at their work.</div>`;
 },dispose(){select.removeEventListener('change',handler);root.removeEventListener('click',clicks);root.replaceChildren();}};
}
