import * as T from 'three';
import {createRoom,createWorkstation,positions} from './office-assets';
import {statusLabels,type DashboardState} from './model';
export function createOffice(host:HTMLElement,onSelect:(id:string)=>void){
 let renderer:T.WebGLRenderer|undefined;let disposed=false;let failed=false;let frame=0;let state:DashboardState|undefined;let scenarioId='';
 const scene=new T.Scene();const camera=new T.OrthographicCamera();camera.position.set(12,13,17);camera.lookAt(0,.5,0);
 scene.add(new T.HemisphereLight('#ffffff','#b1aecb',2.7));const sun=new T.DirectionalLight('#fff7ed',3.2);sun.position.set(-3,12,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.5,far:35});sun.shadow.normalBias=.04;sun.shadow.bias=-.0003;sun.shadow.radius=3;scene.add(sun);
 const room=createRoom();scene.add(room);const workers=new T.Group();scene.add(workers);
 const labels=document.createElement('div');labels.className='scene-labels';
 const labelMap=new Map<string,HTMLButtonElement>();
 function release(group:T.Object3D){const geometries=new Set<T.BufferGeometry>();const materials=new Set<T.Material>();group.traverse(o=>{if(o instanceof T.Mesh){geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}
 function fallback(){failed=true;cancelAnimationFrame(frame);labels.remove();renderer?.domElement.remove();host.querySelector('.scene-fallback')?.remove();const message=document.createElement('div');message.className='scene-fallback';message.innerHTML='<strong>The 3D view is unavailable</strong><p>Your team is still here.<br>Select an agent in the roster to explore their work.</p>';host.append(message);}
 try {const canvas=document.createElement('canvas');const context=canvas.getContext('webgl2',{antialias:true,alpha:true});if(!context)throw new Error('WebGL unavailable');renderer=new T.WebGLRenderer({canvas,context,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;canvas.setAttribute('aria-hidden','true');host.append(canvas,labels);canvas.addEventListener('webglcontextlost',lost);}catch{fallback();}
 function lost(e:Event){e.preventDefault();fallback();}
 function draw(){frame=0;if(disposed||failed||document.hidden||!renderer)return;renderer.render(scene,camera);const width=host.clientWidth,height=host.clientHeight;state?.scenario.agents.forEach((a,i)=>{const [x,z]=positions[i%positions.length];const point=new T.Vector3(x,.24,z+1.62).project(camera);const label=labelMap.get(a.id);if(label){label.style.left=`${(point.x*.5+.5)*width}px`;label.style.top=`${(-point.y*.5+.5)*height}px`;}});}
 function request(){if(!frame&&!disposed&&!failed&&!document.hidden)frame=requestAnimationFrame(draw);}
 function resize(){if(!renderer||failed)return;const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;const aspect=w/h;const view=Math.max(11,16.6/aspect);camera.left=-view*aspect/2;camera.right=view*aspect/2;camera.top=view/2;camera.bottom=-view/2;camera.near=.1;camera.far=80;camera.updateProjectionMatrix();renderer.setSize(w,h,false);request();}
 const observer=new ResizeObserver(resize);observer.observe(host);
 const raycaster=new T.Raycaster();
 function pointer(e:PointerEvent){if(failed||!renderer||!(e.target instanceof HTMLCanvasElement))return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(workers.children,true).find(h=>typeof h.object.userData.agentId==='string');if(hit)onSelect(hit.object.userData.agentId);}
 function labelClick(e:Event){const id=(e.target as Element).closest<HTMLButtonElement>('[data-scene-agent]')?.dataset.sceneAgent;if(id)onSelect(id);}
 function visibility(){if(document.hidden){cancelAnimationFrame(frame);frame=0;}else request();}
 host.addEventListener('pointerup',pointer);labels.addEventListener('click',labelClick);document.addEventListener('visibilitychange',visibility);
 resize();
 return {update(next:DashboardState){state=next;host.dataset.stale=String(!next.scenario.fresh);host.setAttribute('role','group');host.setAttribute('aria-label',next.scenario.agents.length?`Agent office: ${next.scenario.agents.map(a=>`${a.name}, ${statusLabels[a.status]}`).join('; ')}${next.scenario.fresh?'':'. Last sample snapshot'}`:'Agent office: no agents');
 if(scenarioId!==next.scenario.id){scenarioId=next.scenario.id;release(workers);workers.clear();labels.replaceChildren();labelMap.clear();if(!failed)next.scenario.agents.forEach((a,i)=>{const group=createWorkstation(a);const [x,z]=positions[i%positions.length];group.position.set(x,0,z);workers.add(group);const b=document.createElement('button');b.className='scene-label';b.dataset.sceneAgent=a.id;b.setAttribute('aria-label',`Select ${a.name} in office`);b.style.setProperty('--agent',a.color);const dot=document.createElement('i');dot.setAttribute('aria-hidden','true');b.append(dot,document.createTextNode(a.name));labels.append(b);labelMap.set(a.id,b);});}
 workers.children.forEach((g,i)=>{const selected=next.scenario.agents[i]?.id===next.selectedId;const ring=g.getObjectByName('selection-ring');if(ring)ring.visible=selected;});labelMap.forEach((b,id)=>b.setAttribute('aria-pressed',String(id===next.selectedId)));request();
 },dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();document.removeEventListener('visibilitychange',visibility);host.removeEventListener('pointerup',pointer);labels.removeEventListener('click',labelClick);renderer?.domElement.removeEventListener('webglcontextlost',lost);release(scene);renderer?.dispose();host.replaceChildren();}};
}
